# Generated by Django 4.2.5 on 2023-09-23 15:09

import berserk.validators.validator_name
import berserk.validators.validator_password
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0002_alter_advuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='password1',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[berserk.validators.validator_password.Validator_passwod]),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='username',
            field=models.TextField(blank=True, max_length=33, null=True, unique=True, validators=[berserk.validators.validator_name.Validator_name], verbose_name='Username'),
        ),
    ]
