# Generated by Django 4.2.5 on 2023-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0005_alter_advuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerarchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=None, max_length=25)),
            ],
        ),
    ]
