# Generated by Django 4.2.5 on 2023-09-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0006_serarchrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serarchrecord',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
    ]
