# Generated by Django 4.2.5 on 2023-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0007_alter_serarchrecord_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serarchrecord',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=25, verbose_name='Search'),
        ),
    ]
