# Generated by Django 4.2.5 on 2023-09-25 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0009_alter_extrainformation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='br',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
