# Generated by Django 4.2.5 on 2023-09-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0010_alter_br_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrainformation',
            old_name='user',
            new_name='author',
        ),
    ]
