# Generated by Django 4.2.5 on 2023-09-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0011_rename_user_extrainformation_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
        ),
    ]
