# Generated by Django 4.2.5 on 2023-10-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berserk', '0014_alter_imagesadmin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainformation',
            name='age',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
